### ISSUE TITLE
битая иконка при импорте в фоторедактор

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/icons#101]
Перехожу в директорию https://github.com/VKCOM/icons/tree/master/src/svg/28, нахожу incognito_outline_28.svg, при импорте в photoshop, пустая картинка, однако при импорте других иконок таким способом, проблем не обнаружено.

![image](https://user-images.githubusercontent.com/62930989/111043373-032fea80-8464-11eb-9e6e-cfd9445a0d16.png)

![image](https://user-images.githubusercontent.com/62930989/111043380-0d51e900-8464-11eb-8fd5-1e38540ed78c.png)

**Comment by fedorov-xyz** [comment]
Исправили иконку. Проверьте, пожалуйста.
