### ISSUE TITLE
У mention_24 неверная высота и центрирование.

### ISSUE THREAD

**Issue by evtn** [VKCOM/icons#12]
Иконка mention_24 имеет высоту 34px и отцентрирована относительно этой высоты, что вызывает проблемы и жжение в определённых местах.

**Comment by evtn** [comment]
всё ещё не исправлено, будут какие-то изменения?

**Comment by fedorov-xyz** [comment]
Привет, спасибо за issue. Сейчас посмотрим.

**Comment by fedorov-xyz** [comment]
Исправили иконку в версии 1.36.0.
