### ISSUE TITLE
[Feature] Решить вопрос с семантикой

### ISSUE THREAD

**Issue by ArthurStam** [VKCOM/icons#133]
**Проблема**

Исторически, svg-иконка обернута в `div`. Из-за этого, когда иконка попадает в инлайновый элемент (`a`, `button`, `span`, etc.), нарушается семантика дерева.

**Решения**
1. Дать возможность переопределять корневой `div` с помощью свойства `Component`. Плюсы: простое решение. Минусы: ухудшается DX.
2. Заменить `div` на `span` и динамически генерировать тег `style` с `.Icon { display: 'block' }` (`div` по умолчанию блочный и мы должны сохранить эту блочность). Плюсы: DX остаётся на прежнем уровне. Минусы: технически сложное решение.
3. Вообще избавиться от корневого элемента и рисовать `svg`. Плюсы: DX остаётся на прежнем уровне, компонент становится проще. Минусы: что-то может пойти не так.

**Comment by eugpoloz** [comment]
Сделали в https://github.com/VKCOM/icons/pull/287, можно потестировать, поставив себе `@vkontakte/icons@alpha`.
