### ISSUE TITLE
Добавить возможность импорта любой иконки из главного файла

### ISSUE THREAD

**Issue by manaenckow** [VKCOM/icons#15]
Будет гораздо удобней, если иконки будут импортироваться таким образом.

import { Icon24Like } from '@vkontakte/icons';

**Comment by ArthurStam** [comment]
Привет. Сделаем в начале следующего квартала.

**Comment by fedorov-xyz** [comment]
Привет, доступно с версии 1.35.0.

https://github.com/VKCOM/icons/releases/tag/v1.35.0
