### ISSUE TITLE
Избавиться от webpack при сборке иконок

### ISSUE THREAD

**Issue by JWo1F** [VKCOM/icons#2]
Ребята, серьезно? Вы предлагаете тянуть всю эту шапку webpack для каждой иконки? Намного логичнее было бы использовать что-то типа rollup для каждой иконки, тогда оверхед будет минимальным.

**Comment by ArthurStam** [comment]
Скоро пофиксим

**Comment by ArthurStam** [comment]
Перешли с `1.3.1` на самопальную компиляцию из `svg` в `js`. Несжатый `js` теперь весит примерно 1.5 КБ (раньше было около 7).
