### ISSUE TITLE
Использование библиотеки в head'е

### ISSUE THREAD

**Issue by danakt** [VKCOM/icons#23]
В либе используется зависимость `svg-baker-runtime`, которая исполняется сразу при импорте библиотеки в код, она вставляет некоторые элементы в конец body. И если скрипты подключаются из head'а, выглядит это вот так:
![image](https://user-images.githubusercontent.com/1110075/80096520-62e28600-8572-11ea-954c-6b8c884764c7.png)

**Comment by fedorov-xyz** [comment]
Исправлено в версии 1.32.0.
