### ISSUE TITLE
[Question][Build] С версии `v1.157.0` в бандле теперь есть вызов `makeIcon()` 

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/icons#256]
## Описание

Раньше в бандл иконки сразу попадали в "чистую" и вызова `makeIcon()` в рантайме не происходило. Теперь всё наоборот.

## Вопрос

Так и задумано?

#### Версия

`v1.157.0` и больше

#### Скриншоты

<img width="560" alt="image" src="https://user-images.githubusercontent.com/5850354/183690262-b8f53d67-af0c-476c-9dfa-8bf1d3118103.png">

**Рис. 1.** До версии `v1.157.0`

<img width="560" alt="image" src="https://user-images.githubusercontent.com/5850354/183698120-8d408a5e-23c1-4aa1-974b-9469e13c369c.png">

**Рис. 2.** После версии `v1.157.0`

**Comment by fedorov-xyz** [comment]
Так и задумано. `makeIcon` — hoc, который инкапсулирует всю логику, которая раньше дублировалась в каждом файле.

**Comment by inomdzhon** [comment]
> Так и задумано. `makeIcon` — своего рода hoc, который инкапсулирует всю логику, которая раньше дублировалась в каждом файле.

Пон, спасибо за оперативный ответ 🙏 

Смутило, что теперь в рантайме запускается, решил спросить
