### ISSUE TITLE
[Feature] Добавить подгруппы иконок с разделением по платформам

### ISSUE THREAD

**Issue by sumbad** [VKCOM/icons#335]
Было бы удобно дать возможность добавлять и использовать в библиотеке иконки под отдельные платформы, как сейчас, это сделано в VKUI.

<img width="251" alt="image" src="https://user-images.githubusercontent.com/10432330/216271989-987dd56a-700b-426a-a255-effd87d55d6f.png">

К сожалению, на данный момент, для отдельных платформ/сервисов иконки приходится хранить либо в самом проекте, либо устанавливать отдельные дополнительные репозитории с ними. Это ухудшает общую архитектуру проектов, приводит к разным подходам подключения и хранения иконок в них.

**Comment by elizabeth-bennet** [comment]
А есть примеры таких иконок?

**Comment by sumbad** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/10432330/217708980-bb1eedc5-b1e5-4002-9119-b64319c1fdd7.png">

Их не много, и они вроде как даже вписываются в общую парадигму. Поэтому в ходе обсуждения, как я понял, решили просто добавлять такие иконки в общий список.

Поэтому думаю эту issue можно закрыть, спасибо.
