### ISSUE TITLE
Не совпадает копируемый код с изображением иконки

### ISSUE THREAD

**Issue by Artur-Frank** [VKCOM/icons#36]
import Icon28NarrativeOutline from '@vkontakte/icons/dist/28/narrative_outline';

Отличается от указанной в списке иконок.

![image](https://user-images.githubusercontent.com/53945036/91830432-7225be80-ec4b-11ea-8d14-72147f091203.png)

**Comment by fedorov-xyz** [comment]
Привет, спасибо, посмотрим.

**Comment by fedorov-xyz** [comment]
Подскажи используемую версию библиотеки.

**Comment by Artur-Frank** [comment]
Вот в чем причина была =)  

У меня 1.18.2 / устанавливалась с  @vkontakte/create-vk-mini-app
