### ISSUE TITLE
Опечатка в Icon16ClockOutline

### ISSUE THREAD

**Issue by Denior1** [VKCOM/icons#60]
![image](https://user-images.githubusercontent.com/36446798/98468454-ef455500-21f3-11eb-9013-798097fbcb9c.png)

В библиотеке опечатка с иконкой clock размера 16. Вместо outline написано ourline

import Icon16ClockOurline from '@vkontakte/icons/dist/16/clock_ourline';

**Comment by nickname32** [comment]
![image](https://user-images.githubusercontent.com/41116859/99984937-bc3bbd80-2dbe-11eb-9533-a08538186e53.png)

**Comment by nickname32** [comment]
![Frame 1](https://user-images.githubusercontent.com/41116859/99985526-1d639100-2dbf-11eb-9081-92fe95fab6d9.png)

**Comment by fedorov-xyz** [comment]
С версии 1.78.0 доступна иконка с верным неймингом. Старая иконка будет удалена в версии 2.0.0.
