### ISSUE TITLE
Ошибки при компиляции React + Vite

### ISSUE THREAD

**Issue by grisha-sychev** [VKCOM/icons#696]
Добрый день, все было нормально, пока не установил новую версию vk icon

node_modules/@vkontakte/icons/dist/es6/12/add_12.js (1:0) Module level directives cause errors when bundled, "use-client" in "node_modules/@vkontakte/icons/dist/es6/12/add_12.js" was ignored.
node_modules/@vkontakte/icons/dist/es6/12/album_filled_12.js (1:0) Module level directives cause errors when bundled, "use-client" in "node_modules/@vkontakte/icons/dist/es6/12/album_filled_12.js" was ignored.
node_modules/@vkontakte/icons/dist/es6/12/arrow_down_12.js (1:0) Module level directives cause errors when bundled, "use-client" in "node_modules/@vkontakte/icons/dist/es6/12/arrow_down_12.js" was ignored.
node_modules/@vkontakte/icons/dist/es6/12/arrow_up_12.js (1:0) Module level directives cause errors when bundled, "use-client" in "node_modules/@vkontakte/icons/dist/es6/12/arrow_up_12.js" was ignored.
node_modules/@vkontakte/icons/dist/es6/12/arrow_down_circle_12.js (1:0) Module level directives cause errors when bundled, "use-client" in "node_modules/@vkontakte/icons/dist/es6/12/arrow_down_circle_12.js" was ignored.
node_modules/@vkontakte/icons/dist/es6/12/arrow_right_12.js (1:0) Module level directives cause errors when bundled, "use-client" in "node_modules/@vkontakte/icons/dist/es6/12/arrow_right_12.js" was ignored. .... и т д

Я так понял, что в новой версии вы добавили 'use client' для корректного рендера иконок в Next.js 13 React Server Components, это как то влияет на биллинг там где нет Next.js?

**Comment by xeleoss** [comment]
Такая же проблема, но я использую vite + vue. Это сильно замедляет сборку.

**Comment by ivanmem** [comment]
![image](https://github.com/VKCOM/icons/assets/33786293/6d1cbea2-e08c-4392-82b7-5c816d80c8f3)
в версии 2.104.1 проблема осталась

**Comment by SevereCloud** [comment]
@ivanmem проверь пожалуйста что у тебя установлены последние версии vite плагинов и нет дупликации пакета иконок

---

- на уровне vite-plugin-react фиксили в 4 версии https://github.com/vitejs/vite-plugin-react/issues/137

Есть вероятность что это ругаются другие плагины. Как обходной вариант можно в конфигурацию написать

```js
onwarn(warning, warn) {
  if (warning.code === 'MODULE_LEVEL_DIRECTIVE') {
    return
  }
  warn(warning)
}
```

**Comment by ivanmem** [comment]
@SevereCloud в моём проекте нету vite-plugin-react, так как у меня vue 3. 
Делаю импорт иконок с помощью библиотеки [vite-svg-loader](https://www.npmjs.com/package/vite-svg-loader):
```
import Icon28PictureOutline from "@vkontakte/icons/src/svg/28/picture_outline_28.svg?component";
```

**Comment by ivanmem** [comment]
> @ivanmem проверь пожалуйста что у тебя установлены последние версии vite плагинов и нет дупликации пакета иконок
> 
> * на уровне vite-plugin-react фиксили в 4 версии [Handle "use client" warning vitejs/vite-plugin-react#137](https://github.com/vitejs/vite-plugin-react/issues/137)
> 
> Есть вероятность что это ругаются другие плагины. Как обходной вариант можно в конфигурацию написать
> 
> ```js
> onwarn(warning, warn) {
>   if (warning.code === 'MODULE_LEVEL_DIRECTIVE') {
>     return
>   }
>   warn(warning)
> }
> ```

Проблема актуальна, конфиг не помогает
