### ISSUE TITLE
Добавить новую иконку

### ISSUE THREAD

**Issue by seadinkin2002** [VKCOM/icons#73]
Иконка закладки, мне кажется очень полезная для множества кейсов, к примеру в моем она необходима)
![image](https://user-images.githubusercontent.com/62930989/101319138-4554f900-3883-11eb-984d-67a32a94590f.png)

**Comment by astract** [comment]
> Иконка закладки, мне кажется очень полезная для множества кейсов, к примеру в моем она необходима)
> ![image](https://user-images.githubusercontent.com/62930989/101319138-4554f900-3883-11eb-984d-67a32a94590f.png)

Привет. Постараемся залить иконку в ближайшие дни.
