### ISSUE TITLE
Вернуть старую галочку верификации VK

### ISSUE THREAD

**Issue by nesterov021** [VKCOM/icons#74]
Вчера эту иконку убрали и заменили на новую галочку верификации. Новую убирать не нужно, можно, например, вернуть старую иконку галочки VK и назвать, например, old_verified.

**Comment by fedorov-xyz** [comment]
Старая иконка больше не используется в дизайн-системе ВКонтакте, поэтому и в этой библиотеке иконок её больше не будет.
