### ISSUE TITLE
[enhancement] Добавить иконку

### ISSUE THREAD

**Issue by seadinkin2002** [VKCOM/icons#87]
Есть Icon28ThumbsUpOutline, еще к нему хотелось бы Icon28ThumbsUp. Есть конечно Icon24ThumbUp, но это другое.

Пример кейса:
![image](https://user-images.githubusercontent.com/62930989/106250022-e71a1600-6234-11eb-95e5-48e6a5e96341.png)

**Comment by seadinkin2002** [comment]
Не достаточно просто выделения, хотелось бы иконку с заливкой. Пока стоит Icon24ThumbUp, но это очень выделяется.
![image](https://user-images.githubusercontent.com/62930989/106250145-103aa680-6235-11eb-93c5-34772f045c53.png)

**Comment by fedorov-xyz** [comment]
Не уверены, что правильно делать выделение иконок заливкой. Выделение только пункта кажется достаточным. Залитую иконку рисовать не планируем.

**Comment by Lihachyov** [comment]
В похожем случае мы использовали галочку вместо пальца вверх (кнопка Рекомендовать на скриншотах), возможно подойдёт такой вариант? С залитым пальцем в нашем случае выглядело так, будто на эту иконку ещё можно нажать и она просто выделена среди других. Такое восприятие возможно и в твоём случае

Есть ещё вариант использовать иконку лайка (likeOutline + like). У сердечка залитая версия выглядит более понятной и не вызывает вопросов

![IMG_1279](https://user-images.githubusercontent.com/3250391/108402803-0b16b900-722f-11eb-93d7-4de5d2e847c5.PNG)
![IMG_1280](https://user-images.githubusercontent.com/3250391/108402810-0d791300-722f-11eb-80fe-a96ed2c823eb.PNG)
