### ISSUE TITLE
Icon28LogoVkOutline неверного размера

### ISSUE THREAD

**Issue by SIAILYA** [VKCOM/icons#89]
Иконка с логотипом ВК (28 outline) принимает классы и размер иконок 24, из-за чего едет верстка:

![screenshot0510](https://user-images.githubusercontent.com/44904705/107755213-9249c580-6d33-11eb-829c-1ea193a4b2f9.png)
![screenshot0511](https://user-images.githubusercontent.com/44904705/107755207-90800200-6d33-11eb-9a9d-e4cffcedce41.png)
![image](https://user-images.githubusercontent.com/44904705/107755459-e05ec900-6d33-11eb-91fd-6aa2a8c0c8bd.png)

**Comment by fedorov-xyz** [comment]
Привет! Спасибо за issue. Поправим в ближайшее время.

**Comment by fedorov-xyz** [comment]
Исправлено в версии 1.76.0.
