### ISSUE TITLE
Не работает генерация иконок через vkontakte/icons-scripts на Windows

### ISSUE THREAD

**Issue by Heldigb** [VKCOM/icons#920]
Установка по документации. Добавлены иконки для теста.
При попытке сгенерировать получаю пустые сгенеренные файлы где есть пару строчек и ошибку
error TS6053: File C:/Users/Joe/Projects/icons/ts/*.ts  not found. The file is in the program because: Root file specified for compilation.
Проверяли на МаcOS, тот же код и он генерирует корректно. Подскажите , что могло пойти не так ?
`
Error: Command failed: tsc C:\Users\Joe\Projects\icons\ts/**/*.ts C:\Users\Joe\Projects\icons\ts/*.ts --emitDeclarationOnly --declaration --outDir C:\Users\Joe\Projects\icons\dist/typings --jsx react --esModuleInterop --lib "dom,es2015" --skipLibCheck
`

**Comment by SevereCloud** [comment]
Привет, исправление доступно в [v4.2.2](https://github.com/VKCOM/icons/releases/tag/%40vkontakte%2Ficons-scripts%404.2.2)
